### PR TITLE
Chore/prettier eslint

### PR DESCRIPTION
**Pull request by fernandoox**
## Purpose
Coding without a linter o code formatter is a bad idea, we need fucking beautiful code!

## Approach

- I set some tools as eslint, prettier, husky, vscode settings.
- Also, when we try to commit new code, the hook pre-commit will check the unit test and code style, if there is a problem with your code won't be able to be committed

**Important: I don't use vscode however I write some settings, if you don't like those setting, feel free to modify it**

## Where should the reviewer start?
hooks, prettier and eslint rules

## This PR addresses a:
- [ ] Bug
- [ ] Feature
- [ ] Technical Debt
- [X] Chore
- [ ] Vulnerability

### CODE REVIEW

**Comment by ticsaul** [comment]
I think the config is correct but I have a question @fernandoox , Does run SH files in Windows O.S. ?

**Comment by fernandoox** [comment]
> I think the config is correct but I have a question @fernandoox , Does run SH files in Windows O.S. ?

I don't know, that sh file was created by husky automatically 😆, if anyone has Windows O.S could test it.

**Review by ticsaul — APPROVED** [review]
Itś OK.

**Review by oscarmtl7 — COMMENTED** [review]
Look good, Thanks @fernandoox

**Review by oscarmtl7 — APPROVED** [review]

**Pull request merged**
