### PR TITLE
Chore/add readme

### PR DESCRIPTION
**Pull request by fernandoox**
## Purpose
Add some nice information about the project and us

## Approach
- I edited the README.md
- I added the list of contributors

image

## Where should the reviewer start?
Documentation

## This PR addresses a:
- [ ] Bug
- [ ] Feature
- [ ] Technical Debt
- [X] Chore
- [ ] Vulnerability

### CODE REVIEW

**Review by ticsaul — COMMENTED** [review]
We need to define version app and use licence:)

**Comment by jakirock4** [comment]
LGTM 👍

**Review by jakirock4 — APPROVED** [review]
LGTM 👍

**Review by ticsaul — COMMENTED** [review]
It's OK

**Comment by fernandoox** [comment]
> It's OK

@ticsaul if it is ok can you approve the PR?

**Comment by ticsaul** [comment]
Good

**Review by ticsaul — COMMENTED** [review]
Very good!

**Review by ticsaul — APPROVED** [review]
OK

**Pull request merged**
