### PR TITLE
Chore/config api weather

### PR DESCRIPTION
**Pull request by fernandoox**
## Purpose
We need to use an API to get data of weather

## Approach
The API to use is [OpenWeatherMap](https://openweathermap.org/api), I wrote an example of that:
image

## Where should the reviewer start?
Config API, fetch example

## This PR addresses a:
- [ ] Bug
- [ ] Feature
- [ ] Technical Debt
- [X] Chore
- [ ] Vulnerability

### CODE REVIEW

**Comment by oscarmtl7** [comment]
I think you are using the api incorrectly way.
This is the correctly way :
https://api.openweathermap.org/data/2.5/weather?lat=19.4150109&lon=-98.1410678&appid=[{API key}]
Youre final request is :
https://api.openweathermap.org/data/2.5/weather?appid=undefined&lat=19.4150109&lon=-98.1410678

**Comment by fernandoox** [comment]
> I think you are using the api incorrectly way. This is the correctly way : [https://api.openweathermap.org/data/2.5/weather?lat=19.4150109&lon=-98.1410678&appid=[{API](https://api.openweathermap.org/data/2.5/weather?lat=19.4150109&lon=-98.1410678&appid=%5B%7BAPI) key}] Youre final request is : https://api.openweathermap.org/data/2.5/weather?appid=undefined&lat=19.4150109&lon=-98.1410678

The order of the query params doesn't matter, I put at the begin `appid`. Probably, yo need the file `.env` with the line that I share with all of you in private. If you have doubts, you can reach me out. 👍

**Review by jakirock4 — APPROVED** [review]

**Comment by oscarmtl7** [comment]
@fernandoox  The apiConstant.ts should be a apiRoutes.ts file, because in this way we will have benefits in the future such as adding more of our own or third parties apis

**Review by oscarmtl7 — APPROVED** [review]

**Comment by fernandoox** [comment]
> @fernandoox The apiConstant.ts should be a apiRoutes.ts file, because in this way we will have benefits in the future such as adding more of our own or third parties apis

@oscarmtl7 Good thinking! 🥳 . In future, if you see something like that, you cant request me changes before approve de PR, it helps us to improve 🚀

**Pull request merged**
